version: '3'

networks:
  backend:
    #    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24
#          gateway: 172.24.0.1
services:
  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    hostname: localhost
    command: mongod --port 27027
    restart: always
    ports:
      - 27027:27027
    networks:
      backend:
        ipv4_address: 172.24.0.2

  prometheus:
    container_name: "prometheus"
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090   #  <container_port> : <external_port>
    networks:
      backend:
        ipv4_address: 172.24.0.3

  grafana:
    container_name: "grafana"
    image: grafana/grafana
    restart: always
    volumes:
      - /var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      backend:
        ipv4_address: 172.24.0.4

  dbpopulator:
    container_name: "dbpopulatorservice"
    hostname: localhost
    build:
      context: ./
#      context: DBPopulatorService
      dockerfile: Dockerfile
    ports:
      - 8585:8585
      - 8000:8000     # debugging
    expose:
      - 8585
      - 8000          # debugging
    environment:
      - SLACK_URL=${SLACK_URL}
      - MAILTRAP_USERNAME=${MAILTRAP_USERNAME}
      - MAILTRAP_PASSWORD=${MAILTRAP_PASSWORD}
#    depends_on:
#      - mongodb
    networks:
      backend:
        ipv4_address: 172.24.0.5

#  elasticsearch:
#    build: elk/elasticsearch/
#    container_name: elasticsearch
#    ports:
#      - 9200:9200
#      - 9300:9300
#    environment:
#      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
#    networks:
#      backend:
#        ipv4_address: 172.24.0.6
#
#  logstash:
#    build: elk/logstash/
#    container_name: logstash
#    command: -f /etc/logstash/conf.d/
#    volumes:
#      - ./elk/logstash/config:/etc/logstash/conf.d
#    ports:
#      - 9999:9999
#    networks:
#      backend:
#        ipv4_address: 172.24.0.7
#
#  kibana:
#    build: elk/kibana/
#    container_name: kibana
#    volumes:
#      - ./elk/kibana/config/:/opt/kibana/config/
#    ports:
#      - 5601:5601
#    networks:
#      backend:
#        ipv4_address: 172.24.0.8