version: '3'

networks:
  front-tier:
  back-tier:
    driver: bridge

services:
  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    hostname: mongodb
    command: mongod --port 27027
    volumes:
      - ./volumes/dumps:/backup
    restart: always
    expose:
      - "22"
    ports:
      - "27027:27027"
    networks:
      - front-tier

#  prometheus:
#    container_name: "prometheus"
#    image: prom/prometheus
#    restart: always
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#    ports:
#      - "9090:9090"   #  <container_port> : <external_port>
#    networks:
#      - front-tier
#      - back-tier
#
#  grafana:
#    container_name: "grafana"
#    image: grafana/grafana
#    restart: always
#    volumes:
#      - /var/lib/grafana
#    depends_on:
#      - prometheus
#    ports:
#      - "3000:3000"
#    networks:
#      - back-tier

  dbpopulator:
    container_name: "dbpopulatorservice"
    hostname: localhost
    build:
      context: ./
#      context: DBPopulatorService
      dockerfile: Dockerfile
    volumes:
      - ./volumes/dumps/dbpopulator:/opt/backup/
    ports:
      - "8585:8585"
      - "8000:8000"     # debugging
    expose:
      - "8585"
      - "8000"          # debugging
    environment:
      - SLACK_URL=${SLACK_URL}
      - MAILTRAP_USERNAME=${MAILTRAP_USERNAME}
      - MAILTRAP_PASSWORD=${MAILTRAP_PASSWORD}
#    depends_on:
#      - mongodb
    networks:
      - front-tier

  sftp:
    image: writl/sftp
    container_name: "sftp"
    restart: always
    expose:
      - "22"
    ports:
      - "2222:22"
    volumes:
      - ./volumes/dumps/ftp:/data/dumps
    networks:
      - front-tier

############################## ELK STACK ##########################################

#  elasticsearch:
#    build: elk/elasticsearch/
#    container_name: elasticsearch
#    environment:
#      - bootstrap.memory_lock=true
#      - discovery.type=single-node
#      - cluster.name=docker-cluster
#      - network.host=0.0.0.0
##      - es.path.conf=/etc/elasticsearch
#      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    ports:
#      - 9200:9200
#      - 9300:9300
#    expose:
#      - "9200"
#    networks:
#      - back-tier
#
#  logstash:
#    build: elk/logstash/
#    container_name: logstash
#    volumes:
#      - ./elk/logstash/config:/etc/logstash/conf.d
#    command: -f /etc/logstash/conf.d/
#    ports:
#      - 9600:9600
#      - 9999:9999
#    networks:
#      - front-tier
#      - back-tier
#
#  kibana:
#    build: elk/kibana/
#    container_name: kibana
#    volumes:
#      - ./elk/kibana/config/:/opt/kibana/config/
#    ports:
#      - 5601:5601
#    networks:
#      - back-tier